### ISSUE TITLE
lag with big tiles

### ISSUE THREAD

**Issue by Jodediah** [zenzoa/mosi#17]
character moves slower in a room filled with tiles than they do in an empty room. first noticed this at 15 pixels/tile, was able to reproduce with 17px/tile.

**Comment by Jodediah** [comment]
I'm using môsi from chrome on my android phone!! realized this might be relevant after posting

**Comment by sarahgould** [comment]
Yeah, I’ve seen some performance issues occasionally even on desktop. This helps give me a specific angle at the problem, though, and I’ll keep digging even I’m not great at figuring out why things are slow! 😓

**Comment by sarahgould** [comment]
Ok, I'm adding a bunch of performance fixes in the next big release, which should be out shortly.

**Comment by sarahgould** [comment]
Just updated a bunch of stuff, including performance. Want to give it a try on the github.io version?

**Comment by Jodediah** [comment]
can do! give me a few days and wish me good luck in remembering lol
