### ISSUE TITLE
Cannot Control Game Using Itch.io's Fullscreen mode

### ISSUE THREAD

**Issue by Limisios** [zenzoa/mosi#23]
When I press the fullscreen button to play my game on [itch.io](https://limisios.itch.io/old-world), the game does go to full screen but I cannot use any of the arrow key controls. I can press `esc` to leave fullscreen but I still cannot control the game until I refresh the page.

**System information**
MacOS 10.14.4
Firefox 66.0.3 (64-bit) + Safari 12.1

**Comment by sarahgould** [comment]
Huh... weirdly this happens to me with Bitsy games too. I wonder if it has to do with the way MacOS does fullscreen?

**Comment by Limisios** [comment]
I tried to play the game in fullscreen on Firefox on a Windows 10 computer and got the same result. Interestingly, I noticed that you can control the character by clicking and dragging the mouse. This works on both PC and Mac.

**Comment by sarahgould** [comment]
Still looking into this... Bitsy games are working for me again, so it's definitely something I should be able to fix. But I can't figure out how Bitsy initializes event handlers differently from mosi!

**Comment by sarturodev** [comment]
I've fixed the fullscreen mode bug.  This is the pull request: https://github.com/zenzoa/mosi/pull/36
