### ISSUE TITLE
Textarea:UI layout is broken by activating the keyboard on Android devices

### ISSUE THREAD

**Issue by s0liv0** [zenzoa/mosi#30]
**mosi version:** 
V 1.0 

**OS/Device:**
OS:Android 9.0
Device: Nokia 1

**Browser:**
Google Chrome 78.0.3904.62

**Issue Description:**
By activating the Android keyboard from the Script panel textarea. The layout is broken. Also, the textarea is set to a minimum width.

**Steps to reproduce:**
1-Open the Script panel
2-Tap on the textarea to active the Android keyboard.

![2019_11_10_15 51 10](https://user-images.githubusercontent.com/24869615/68549757-2c54ec80-03d2-11ea-8e41-388d3137481e.jpg)

**Comment by s0liv0** [comment]
I found a solution and I've uploaded the changes to the fork:  https://github.com/s0liv0/mosi

**Comment by zenzoa** [comment]
Awesome! Want to do a pull request for this?

**Comment by s0liv0** [comment]
it will be a pleasure! It's an amazing tool, I will continue to support it
