### ISSUE TITLE
Music is really loud

### ISSUE THREAD

**Issue by cosmicchipsocket** [zenzoa/mosi#33]
Through a small phone speaker the music volume is fine but on desktop I have to turn the audio down to about 25-33% of what I normally use because it's so loud. It heavily peaks the audio too so it sounds all scratchy. Could the volume be lowered by 12 dB (25% of original volume) at the very least?

**Comment by zenzoa** [comment]
I've reduced the volume by half, which seems to produce a reasonable result. Let me know what you think.
