### ISSUE TITLE
Change Font?

### ISSUE THREAD

**Issue by st33d** [zenzoa/mosi#34]
The default font in the sample project is barely readable to me and looks harsh and aggressive compared to Bitsy. I wouldn’t want to spend prolonged amounts of time reading that font and yet I would be forced to do so playing a Mosi game.

Is there a way to change it? If there isn’t, please consider an alternative font, it’s acceptable for one sentence or a title screen but not for any extended amount of reading.

**Comment by zenzoa** [comment]
You can change the font for your game! Mosi supports the bitsy font format, and there are some cool bitsy fonts on itch.io (and you can also download the original bitsy fonts from bitsy itself: http://ledoux.io/bitsy/editor.html). Here's instructions for importing new fonts to mosi: https://github.com/zenzoa/mosi/wiki/World
