### ISSUE TITLE
[Bug] Moving/Removing a sprite on Room Load locks up

### ISSUE THREAD

**Issue by Jademalo** [zenzoa/mosi#38]
I had a sprite that I wanted to move once the player had advanced past a specific state. Since it's not possible to remove sprites that are in different rooms, I had a check on entering a specific room that if you had an item, it would remove the sprite.

This didn't work, and caused the game to hang. I had to move that check to a trigger tile that you press after loading the room, and that worked fine, though was a bit janky.

**Comment by zenzoa** [comment]
Can you share the script that cause the game to hang?

**Comment by Jademalo** [comment]
Ok, this produces a consistent crash.

- Set up a sprite, put it at 1 10 in the first room
- On enter of the second room, increment the variable to 1
- On moving back to the first room with the following code in on enter, the game will hang

```{if {eq {var car-bee-state} 1}}
Oh no, I'm going to bee late!
{pick {sprite-at 1 10}}{remove-sprite}{/pick}
{inc-var car-bee-state}
{/if}```

If this is run on room load, the game will hang. If it is run anywhere else, it is fine.

**Comment by zenzoa** [comment]
Thanks for the detailed repro steps! I just pushed an update that should let you run {pick} successfully from room scripts.

**Comment by Jademalo** [comment]
Awesome, thank you so much for the quick turnaround!
