### ISSUE TITLE
Add Subheading for Else Method in Wiki

### ISSUE THREAD

**Issue by Limisios** [zenzoa/mosi#40]
It might be useful if the `{else}` function in the [wiki](https://github.com/zenzoa/mosi/wiki/Scripts#if-bool--if) could have its own subheading. (Or at least include `{else}` in the current subheading.) I mostly skim through the headings when looking at what code is possible and I completely missed the fact that there's an else function available.

_(Can you tell this problem only occurred for me because I was not reading the documentation thoroughly enough 😝 )_

**Comment by zenzoa** [comment]
Good idea - changed the header to {if [bool} ... {else} ... {/if}
