### ISSUE TITLE
Unable to Access Particular Song in Editing Menu

### ISSUE THREAD

**Issue by Limisios** [zenzoa/mosi#41]
I can't seem to access a particular song in my project. I can select any other song easily, but this one particular song can't be selected to be edited unless I select it to be used in one of the rooms, after that if I select another song and try to return to the faulty song, the bug returns. This happens even after resetting the program and the computer.

![MusicBug](https://user-images.githubusercontent.com/16746836/120179985-29635c00-c203-11eb-8c1d-346a602f4aa0.gif)
![MusicBug2](https://user-images.githubusercontent.com/16746836/120180521-c32b0900-c203-11eb-9c9c-eee6661b323f.gif)

Edit: I've just managed to work out that the song that I can't select to edit seems to be whichever song is currently assigned to the room that I'm editing.

**Comment by zenzoa** [comment]
Good catch! Fixed it!
