### ISSUE TITLE
[feature] backup and restore

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [zenzoa/mosi#43]
so yes. i have a general problem in browser, that every reboot my lap loses cookies (idfk why) and cant save web storage ;-; .
my idea is - to be able to export such game to a file (either html or custom one), so i can load later and continue.
pls...

BTW  - cool engine, gonna make custom "zelda" out of it ;p (WHEN BACKUP WILL BE !!!)

**Comment by zenzoa** [comment]
You can export your game file - in the world panel, press the button with the world name on it, and then go down to 'export.'
<img width="347" alt="image" src="https://user-images.githubusercontent.com/10480278/173134490-05de97ca-4108-42af-b0ad-659a62ba2b46.png">
<img width="435" alt="image" src="https://user-images.githubusercontent.com/10480278/173134562-5f88a873-7e27-4221-964e-22d332488938.png">
<img width="427" alt="image" src="https://user-images.githubusercontent.com/10480278/173134575-3077a041-433f-495e-9fa0-ef56e0a1f079.png">
There's also a blurp on the wiki about it: https://github.com/zenzoa/mosi/wiki/World

**Comment by hacknorris-aka-penguin** [comment]
but i was saying not about world but a full game? like all the sprites...
like ability to import shared game or smth...
@zenzoa

**Comment by zenzoa** [comment]
Hm not sure what you mean. Exporting the world includes all the sprites in it.

**Comment by hacknorris-aka-penguin** [comment]
means - like using this : https://github.com/zenzoa/mosi/wiki#share-your-creation ?

**Comment by zenzoa** [comment]
Oooh do you mean while you're playing, save where you're at, and resume playing from that point later? For longer games?

**Comment by hacknorris-aka-penguin** [comment]
no, when editing - to include scripts and all the rest in exactly same place as saved...

**Comment by hacknorris-aka-penguin** [comment]
cu i do a little bigger thing =]

**Comment by zenzoa** [comment]
Sorry, I'd love to help, but I don't quite understand what you're asking for. Maybe if you walked through how you would use this feature?

**Comment by hacknorris-aka-penguin** [comment]
means - can export world save scripts and all the rest?

**Comment by zenzoa** [comment]
What does the current export feature not do for you?

**Comment by hacknorris-aka-penguin** [comment]
hmm... idk, never tested... first time i use (godot was too hard for me lool)
